modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="shinyhorses"
version="1.1"
displayName="Shiny Horses Forge - Enchantable Horse Armor"
credits="Credit goes to tfarecnim for the original mod and Dragonostic for the Fabric version."
displayURL="https://www.curseforge.com/minecraft/mc-mods/shiny-horses-forge-enchantable-horse-armor"
authors="Kuraion"
logoFile="logo.png"
description='''Enchant horse armor and gallop over the freezing ocean!'''

[[dependencies.ante]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,]"
    ordering="NONE"
    side="BOTH"




